<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('productos')->insert([
            [
                'id' => 101,
                'nombre' => 'Smart TV 55 Pulgadas 4K',
                'sku' => 'TV-55-4K-01',
                'categoria' => 'Electrónica',
                'precio' => 450.00,
                'stock' => 15,
                'activo' => true,
                'fecha_registro' => '2025-01-15 10:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'nombre' => 'Audífonos Bluetooth Pro',
                'sku' => 'AUD-BT-02',
                'categoria' => 'Electrónica',
                'precio' => 89.99,
                'stock' => 45,
                'activo' => true,
                'fecha_registro' => '2025-02-20 11:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'nombre' => 'Laptop Pro 16GB RAM',
                'sku' => 'LAP-PRO-16',
                'categoria' => 'Cómputo',
                'precio' => 1200.00,
                'stock' => 8,
                'activo' => true,
                'fecha_registro' => '2025-03-05 09:15:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'nombre' => 'Mouse Ergonómico',
                'sku' => 'MOU-ERG-04',
                'categoria' => 'Cómputo',
                'precio' => 35.50,
                'stock' => 120,
                'activo' => true,
                'fecha_registro' => '2025-04-12 14:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'nombre' => 'Refrigerador No Frost 400L',
                'sku' => 'REF-NF-400',
                'categoria' => 'Línea Blanca',
                'precio' => 650.00,
                'stock' => 5,
                'activo' => true,
                'fecha_registro' => '2025-05-18 16:45:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'nombre' => 'Tenis Deportivos Running',
                'sku' => 'TEN-RUN-88',
                'categoria' => 'Moda',
                'precio' => 75.00,
                'stock' => 60,
                'activo' => true,
                'fecha_registro' => '2025-06-01 12:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'nombre' => 'Chaqueta de Cuero Sintético',
                'sku' => 'CHA-CUE-07',
                'categoria' => 'Moda',
                'precio' => 120.00,
                'stock' => 25,
                'activo' => true,
                'fecha_registro' => '2025-06-15 08:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'nombre' => 'Sofá Cama Contemporáneo',
                'sku' => 'SOF-CAM-05',
                'categoria' => 'Hogar y Cocina',
                'precio' => 350.00,
                'stock' => 12,
                'activo' => true,
                'fecha_registro' => '2025-07-02 11:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'nombre' => 'Cafetera de Goteo Programable',
                'sku' => 'CAF-GOT-09',
                'categoria' => 'Hogar y Cocina',
                'precio' => 45.00,
                'stock' => 40,
                'activo' => true,
                'fecha_registro' => '2025-07-22 15:20:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'nombre' => 'Bicicleta de Montaña R29',
                'sku' => 'BIC-MON-29',
                'categoria' => 'Deportes',
                'precio' => 580.00,
                'stock' => 7,
                'activo' => true,
                'fecha_registro' => '2025-08-05 09:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'nombre' => 'Set de Mancuernas 20kg',
                'sku' => 'SET-MAN-20',
                'categoria' => 'Deportes',
                'precio' => 65.00,
                'stock' => 30,
                'activo' => true,
                'fecha_registro' => '2025-08-19 17:10:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 112,
                'nombre' => 'Libro: Clean Code',
                'sku' => 'LIB-CC-2022',
                'categoria' => 'Libros',
                'precio' => 42.00,
                'stock' => 50,
                'activo' => true,
                'fecha_registro' => '2025-09-01 10:45:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 113,
                'nombre' => 'Set de Bloques de Construcción',
                'sku' => 'JUG-BLO-13',
                'categoria' => 'Juguetes',
                'precio' => 29.99,
                'stock' => 85,
                'activo' => true,
                'fecha_registro' => '2025-09-15 14:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 114,
                'nombre' => 'Compresor de Aire Portátil',
                'sku' => 'AUT-COM-14',
                'categoria' => 'Automotriz',
                'precio' => 55.00,
                'stock' => 18,
                'activo' => true,
                'fecha_registro' => '2025-10-02 11:15:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 115,
                'nombre' => 'Sérum Facial Ácido Hialurónico',
                'sku' => 'BEL-SER-15',
                'categoria' => 'Belleza',
                'precio' => 24.50,
                'stock' => 100,
                'activo' => false,
                'fecha_registro' => '2025-10-20 16:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::statement("SELECT setval(pg_get_serial_sequence('productos', 'id'), (SELECT MAX(id) FROM productos))");
    }
}
